import styles from '../styles/Home.module.scss'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>WeCare Healthcare Services @</title>
        <meta name="Healthcare application" content="Generated by create next app" />
      </Head> */}
        <header>
          <nav>
            <ul className = {styles.navbar}>
              <li><Link href='/login' className={styles.link}>Sign In</Link></li>
              <li><Link href='/About'>About Us</Link></li>
              <li><Link href='/Contact'>Contact Us</Link></li>
            </ul>
          </nav>
        </header>
        <main className={styles.main}>
        <h1 className={styles.title}> Welcome to WeCare Healthcare</h1>
        </main>
        <footer>
          <span>@WeCare Healthcare Services</span>
        </footer>
    </div>
  )
}
